config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get '/', to: "main#index"
    get 'requests', to: 'requests#index'
    get 'users', to: 'users#index'
    get 'posts', to: 'posts#index'
  end

  match "/404",                             :to => "errors#not_found",              :via => :all
  match "/500",                             :to => "errors#internal_server_error",  :via => :all
  match "/422",                             :to => "errors#denied",       :via => :all

  get '/robots.:format' => 'home#robots'
  get '/sitemap.xml' => 'home#sitemaps', :format => "xml"


  authenticate :user, lambda { |u| u.super_admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
  mount ActionCable.server => "/cable"


  authenticated :user do
    root 'user#index' ,                     as: :authenticated_root
  end
  
  root 'home#index'


  namespace :api , defaults: {format: 'json'} do
    get 'notifications',                     to: 'notifications#index'
    get 'following',                          to: 'user#index'
   end

  namespace :wtf do
    get '/', to: '/wtf#index'
    get 'about', to: 'about#index'
    get 'support', to: 'support#index'
    get 'features', to: 'features#index'
    get 'policies/rules'
    get 'policies/terms'
    get 'policies/privacy'
  end

  post 'join',                              to: 'requests#create'
  get 'join',                               to: 'requests#new',                         as: :new_requests
  get 'requested',                          to: 'requests#requested',                   as: :requested

  devise_for :users, skip: :all, controllers: {
    sessions: 'devise/users/sessions',
    passwords: 'devise/users/passwords',
    registrations: 'devise/users/registrations',
    confirmations: 'devise/users/confirmations',
    invitations: 'devise/users/invitations',
  }

  devise_scope :user do
  get 'login',                            to: 'devise/users/sessions#new',          as: :new_user_session
  post 'login',                           to: 'devise/users/sessions#create',       as: :user_session
  get 'logout',                           to: 'devise/users/sessions#destroy',      as: :destroy_user_session

  get 'secret/new',                       to: 'devise/users/passwords#new',         as: :new_user_password
  get 'secret/edit',                      to: 'devise/users/passwords#edit',        as: :edit_user_password
  patch 'secret',                         to: 'devise/users/passwords#update',      as: :user_password
  put 'secret',                           to: 'devise/users/passwords#update'
  post 'secret',                          to: 'devise/users/passwords#create'

  get 'userinfo',                         to: 'devise/users/registrations#edit',    as: :edit_user_registration
  patch 'userinfo',                       to: 'devise/users/registrations#update',  as: :user_registration
  put 'userinfo',                         to: 'devise/users/registrations#update',  as: :user
  delete 'userinfo',                      to: 'devise/users/registrations#destroy'
  post 'userinfo',                        to: 'devise/users/registrations#create'


  get 'users/confirm',                    to: 'devise/users/confirmations#show',    as: :user_confirmation
  post 'users/confirm',                   to: 'devise/users/confirmations#create'

  get 'chosen-one/accept',                to: 'devise/users/invitations#edit',      as: :accept_user_invitation
  get 'chosen-one/decline',               to: 'devise/users/invitations#destroy',   as: :remove_user_invitation
  get 'invite',                           to: 'devise/users/invitations#new',       as: :new_user_invitation
  patch 'users/invitation',               to: 'devise/users/invitations#update',    as: :user_invitation
  put 'users/invitation',                 to: 'devise/users/invitations#update'
  post 'invite',                          to: 'devise/users/invitations#create'
  end

  get 'user/:username' => 'user#show',      :constrain => { :username => /[a-zA-Z-]+/ }, as: :profile
  get 'followings',                          to: 'user#index'

  resources :user, :only => [:show] do
    member do
      get :follow
      get :unfollow
    end
  end

  get 'discover',                           to: 'post#index',            as: :discover
  get 'create',                             to: 'post#new',              as: :new_post
  get 'post/:url/edit',                     to: 'post#edit',             as: :edit_post
  get 'post/:url',                          to: 'post#show',             as: :post
  delete 'post/:url',                       to: 'post#destroy'

  post 'texts',                             to: 'post/texts#create',      as: :post_texts
  get 'new/text',                           to: 'post/texts#new',         as: :new_text
  patch 'post/:url',                        to: 'post#update' ,          as: :post_text

  post 'images',                            to: 'post/images#create',     as: :post_images
  get 'new/image',                          to: 'post/images#new',        as: :new_image
  patch 'post/:url',                         to: 'post#update' ,          as: :post_image

  post 'audios',                            to: 'post/audios#create',     as: :post_audios
  get 'new/audio',                          to: 'post/audios#new',        as: :new_audio
  patch 'post/:url',                         to: 'post#update' ,          as: :post_audio

  post 'videos',                            to: 'post/videos#create',     as: :post_videos
  get 'new/video',                          to: 'post/videos#new',        as: :new_video
  patch 'post/:url',                         to: 'post#update' ,          as: :post_video

  post 'post/:url/comments',                 to: 'comments#create',   as: :post_comments
  delete 'post/:url/comment/:comment_id',    to: 'comments#destroy',  as: :post_comment

  get "hashtags/:hashtag",                  to: "hashtags#show",          as: :hashtag

  get 'search',                             to: "search#index",           as: :search



  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  
  resources :post do
    member do
      post :repost
    end
  end

  get 'challenges',             to: 'challenges#index',   as: :challenges
  post 'new/challenge',         to: 'challenges#create'
  get 'new/challenge',          to: 'challenges#new'
  get 'challenge/:id/edit',     to: 'challenges#edit',    as: :edit_challenge
  get 'challenge/:id',          to: 'challenges#show',    as: :challenge
  patch 'challenge/:id',        to: 'challenges#update'
  put 'challenge/:id',          to: 'challenges#update'
  delete 'challenge/:id',        to: 'challenges#destroy'

  get 'challenge/:id/submit',          to: 'challenges#submit'




end

app/models/user.rb
class User < ApplicationRecord
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :async, :validate_on_invite => true

  has_many :posts,          dependent:  :destroy
  has_many :comments,       dependent:  :destroy
  has_many :notifications,  dependent:  :destroy
  has_many :challenges,  dependent:  :destroy
  has_many :user_interests, dependent:  :destroy
  has_many :interests,      dependent:  :destroy, through:    :user_interests
  has_one :crate

  validates_uniqueness_of :username, allow_blank: true

  #Role
  enum access_level: { user: 0, admin: 1, super_admin: 2}

  #JSONB Storext
  include Storext.model
  store_attributes :preferences do
    hide_nsfw Boolean, default: true
  end

  #Followable
  acts_as_follower
  acts_as_followable

  #Rememberable by default
  def remember_me
   true
  end

  ## => Only require current password for Email and Password change
  validates_confirmation_of :password
  
  def update_with_password(params={})
    if params[:password].blank?
      params.delete(:current_password)
      self.update_without_password(params)
    else
      self.verify_password_and_update(params)
    end
  end

  def update_without_password(params={})
    params.delete(:password)
    params.delete(:password_confirmation)
    result = update_attributes(params)
    clean_up_passwords
    result
  end

  def verify_password_and_update(params)
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = if valid_password?(current_password)
      update_attributes(params)
    else
      self.attributes = params
      self.valid?
      self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
      false
    end
    clean_up_passwords
    result
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::MainController
  def index
    @registered_users = User.where.not(invitation_accepted_at: nil,)
    @registered_users = User.all.where.not(invitation_accepted_at: nil)
    @active_daily_users = @registered_users.where("last_seen_at > ?", 1.day.ago)
    @active_weekly_users = @registered_users.where("last_seen_at > ?", 1.week.ago)
    @active_monthly_users = @registered_users.where("last_seen_at > ?", 1.month.ago)
  end
end

app/controllers/api/user_controller.rb
class Api::UserController  < ActionController::API
    before_action :find_user
    before_action :authenticate_user!
  
    def index
      @users = current_user.all_following
    end
  
    private
  
    def find_user
      @user = User.find_by_username(params[:username])
    end

  end
  

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :find_user
  before_action :authenticate_user!
  
  # Followings page
  def index
    @users = current_user.all_following
    if current_user.hide_nsfw == true
      @posts = Post.safe.except_who(current_user).followed(@users).public_post
    else
      @posts = Post.posted.except_who(current_user).followed(@users).public_post
    end
  end
  
  # Profile Page 
  def show
      raise ActionController::RoutingError.new('Not Found') if @user.blank?

      if current_user.hide_nsfw == true && current_user != @user
        @posts = @user.posts.safe.public_post
      else
        @posts = @user.posts.posted
      end

      # Follow button 
      def follow
        @user = User.find(params[:id])
        current_user.follow(@user)
        redirect_back(fallback_location: root_path)
      end
      
      # Unfollow button
      def unfollow
        @user = User.find(params[:id])
        current_user.stop_following(@user)
        redirect_back(fallback_location: root_path)
      end
  end

  private

  def find_user
    @user = User.find_by_username(params[:username])
  end
end

app/views/user/_profile-card.html.erb
<% unless @users.blank? %>	
	<div id="user-all">
		<div class="profiles masonry transitions-enabled">
			<% users.each do |user| %>
			<div id="profile-card">
				<div class="profile-card">
					<a href="/user/<%= user.username %>">
                        <div class="body">
                            <div class="name">
                                <%= user.name%>
                            </div>
                            <div class="username">
                                @<%= user.username %>
                            </div>
                            <% if user.bio? %>
                                <div class="bio">
                                    <%= user.bio %>
                                </div>
                            <% end %>
                        </div>
                    </a>
					<div class="footer">
						<div class="buttons">
                            <% if user_signed_in? %>
                            <% unless user != current_user %>
                                <a class="settings" href="/userinfo">
                                <button type="button" name="button"> Settings </button>
                                </a>
                            <% else %>
                                <% if current_user.following?(user) %>
                                <a class="settings" href="<%= unfollow_user_path(user) %>">
                                    <button type="button" name="button"> Unsubscribe</button>
                                </a>
                                <% else %>
                                <a class="settings" href="<%= follow_user_path(user) %>">
                                    <button type="button" name="button"> Subscribe </button>
                                </a>
                                <% end %>
                            <% end %>
                            <% end %>
                        </div>
					</div>
				</div>
			</div>
			<%end %>
		</div>
	</div>
<% end %>					
	<script>
		var $grid = $('.masonry').imagesLoaded( function() { $grid.masonry({ itemSelector: '.profile-card', columnWidth: '.profile-card', horizontalOrder: true, percentPosition: true, gutter: 25}); });
	</script>

app/views/user/index.html.erb
<%= render '/navigation/mobile-home'%>
<div id="discover">
    <div id="following">
        <%= render 'post/posts', posts: @posts%>
    </div>
</div>

app/views/user/show.html.erb
<div id="profile">
  <div class="sections">
    <div class="section-1">
      <div class="user">
        <div class="info">
          <div class="name">
            <%= @user.name %>
          </div>
          <div class="username">
            @<%= @user.username %>
          </div>
          <div class="bio">
            <%= @user.bio %>
          </div>
          <div class="interests flex">
            <% @user.interests.each do |interest| %>
              <div class="interest">
                <%= interest.name%>
              </div>
            <% end %>
          </div>
          <div class="buttons">
            <% if user_signed_in? %>
              <% unless @user != current_user %>
                <a class="settings" href="/userinfo">
                  <button type="button" name="button"> Settings </button>
                </a>
              <% else %>
                <% if current_user.following?(@user) %>
                  <a class="settings" href="<%= unfollow_user_path(@user) %>">
                    <button type="button" name="button"> Unsubscribe </button>
                  </a>
                <% else %>
                  <a class="settings" href="<%= follow_user_path(@user) %>">
                    <button type="button" name="button"> Subscribe </button>
                  </a>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr/>
    <div class="section 2">
      <%= render 'post/posts', posts: @posts %>
    </div>
  </div>
</div>